IG_EMAILS = {
    "cybersecurity":      "cyberlead@email.com",
    "gen ai":             "genaileadlead@email.com",
    "web development":    "weblead@email.com",
    "project management": "pmlead@email.com",
    "devops":             "devopslead@email.com",
    "game dev":           "gamelead@email.com",
    "no or low code":     "lowcodelead@email.com",
    "entrepreneurship":   "entlead@email.com",
    "ui ux":              "uiuxlead@email.com",
    "mobile development": "mobilelead@email.com",
    "data analytics":     "datalead@email.com",
    "ai":                 "ailead@email.com",
    "digital marketing":  "marketinglead@email.com",
    "dsa":                "dsalead@email.com",
    "human resource":     "hrlead@email.com",
    "blockchain":         "blockchainlead@email.com",
    "data science":       "datascienceleadlead@email.com",
    "iot":                "iotlead@email.com",
    "general tech":       "generallead@email.com",
}