outputs:

  console:
    active: true
    type: console
    show_fields: [ig, category, deadline, score, title] # Added deadline and reordered

  json_file:
    active: true
    type: json_file
    path: output/results.json
    pretty: true

  csv_file:
    active: false
    type: csv_file
    path: output/results.csv
